"""initial tables

Revision ID: d9bd9702c2a1
Revises: 
Create Date: 2026-02-21 20:31:39.925117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9bd9702c2a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_application', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'candidate_application', 'job_listing', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interview', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('interview_candidate_application_id_key'), 'interview', type_='unique')
    op.create_foreign_key(None, 'interview', 'candidate_application', ['candidate_application_id'], ['id'], ondelete='CASCADE')

    
    op.alter_column(
        'job_listing',
        'status',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum('open', 'closed', name='jobstatus'),
        postgresql_using="status::jobstatus",
        existing_nullable=True
    )
    op.alter_column('profile', 'experience_years',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_foreign_key(None, 'profile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.alter_column('profile', 'experience_years',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('job_listing', 'status',
               existing_type=sa.Enum('open', 'closed', name='jobstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_unique_constraint(op.f('interview_candidate_application_id_key'), 'interview', ['candidate_application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('interview', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'candidate_application', type_='foreignkey')
    op.alter_column('candidate_application', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
